/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WhyWeBuiltHppRouteImport } from './routes/why-we-built-hpp'
import { Route as HomeownerCoverageRouteImport } from './routes/homeowner-coverage'
import { Route as FileAClaimRouteImport } from './routes/file-a-claim'
import { Route as CoverageOptionsRouteImport } from './routes/coverage-options'
import { Route as ContractorSignupRouteImport } from './routes/contractor-signup'
import { Route as BecomeAContractorRouteImport } from './routes/become-a-contractor'
import { Route as IndexRouteImport } from './routes/index'

const WhyWeBuiltHppRoute = WhyWeBuiltHppRouteImport.update({
  id: '/why-we-built-hpp',
  path: '/why-we-built-hpp',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeownerCoverageRoute = HomeownerCoverageRouteImport.update({
  id: '/homeowner-coverage',
  path: '/homeowner-coverage',
  getParentRoute: () => rootRouteImport,
} as any)
const FileAClaimRoute = FileAClaimRouteImport.update({
  id: '/file-a-claim',
  path: '/file-a-claim',
  getParentRoute: () => rootRouteImport,
} as any)
const CoverageOptionsRoute = CoverageOptionsRouteImport.update({
  id: '/coverage-options',
  path: '/coverage-options',
  getParentRoute: () => rootRouteImport,
} as any)
const ContractorSignupRoute = ContractorSignupRouteImport.update({
  id: '/contractor-signup',
  path: '/contractor-signup',
  getParentRoute: () => rootRouteImport,
} as any)
const BecomeAContractorRoute = BecomeAContractorRouteImport.update({
  id: '/become-a-contractor',
  path: '/become-a-contractor',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/become-a-contractor': typeof BecomeAContractorRoute
  '/contractor-signup': typeof ContractorSignupRoute
  '/coverage-options': typeof CoverageOptionsRoute
  '/file-a-claim': typeof FileAClaimRoute
  '/homeowner-coverage': typeof HomeownerCoverageRoute
  '/why-we-built-hpp': typeof WhyWeBuiltHppRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/become-a-contractor': typeof BecomeAContractorRoute
  '/contractor-signup': typeof ContractorSignupRoute
  '/coverage-options': typeof CoverageOptionsRoute
  '/file-a-claim': typeof FileAClaimRoute
  '/homeowner-coverage': typeof HomeownerCoverageRoute
  '/why-we-built-hpp': typeof WhyWeBuiltHppRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/become-a-contractor': typeof BecomeAContractorRoute
  '/contractor-signup': typeof ContractorSignupRoute
  '/coverage-options': typeof CoverageOptionsRoute
  '/file-a-claim': typeof FileAClaimRoute
  '/homeowner-coverage': typeof HomeownerCoverageRoute
  '/why-we-built-hpp': typeof WhyWeBuiltHppRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/become-a-contractor'
    | '/contractor-signup'
    | '/coverage-options'
    | '/file-a-claim'
    | '/homeowner-coverage'
    | '/why-we-built-hpp'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/become-a-contractor'
    | '/contractor-signup'
    | '/coverage-options'
    | '/file-a-claim'
    | '/homeowner-coverage'
    | '/why-we-built-hpp'
  id:
    | '__root__'
    | '/'
    | '/become-a-contractor'
    | '/contractor-signup'
    | '/coverage-options'
    | '/file-a-claim'
    | '/homeowner-coverage'
    | '/why-we-built-hpp'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BecomeAContractorRoute: typeof BecomeAContractorRoute
  ContractorSignupRoute: typeof ContractorSignupRoute
  CoverageOptionsRoute: typeof CoverageOptionsRoute
  FileAClaimRoute: typeof FileAClaimRoute
  HomeownerCoverageRoute: typeof HomeownerCoverageRoute
  WhyWeBuiltHppRoute: typeof WhyWeBuiltHppRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/why-we-built-hpp': {
      id: '/why-we-built-hpp'
      path: '/why-we-built-hpp'
      fullPath: '/why-we-built-hpp'
      preLoaderRoute: typeof WhyWeBuiltHppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/homeowner-coverage': {
      id: '/homeowner-coverage'
      path: '/homeowner-coverage'
      fullPath: '/homeowner-coverage'
      preLoaderRoute: typeof HomeownerCoverageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/file-a-claim': {
      id: '/file-a-claim'
      path: '/file-a-claim'
      fullPath: '/file-a-claim'
      preLoaderRoute: typeof FileAClaimRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coverage-options': {
      id: '/coverage-options'
      path: '/coverage-options'
      fullPath: '/coverage-options'
      preLoaderRoute: typeof CoverageOptionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contractor-signup': {
      id: '/contractor-signup'
      path: '/contractor-signup'
      fullPath: '/contractor-signup'
      preLoaderRoute: typeof ContractorSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/become-a-contractor': {
      id: '/become-a-contractor'
      path: '/become-a-contractor'
      fullPath: '/become-a-contractor'
      preLoaderRoute: typeof BecomeAContractorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BecomeAContractorRoute: BecomeAContractorRoute,
  ContractorSignupRoute: ContractorSignupRoute,
  CoverageOptionsRoute: CoverageOptionsRoute,
  FileAClaimRoute: FileAClaimRoute,
  HomeownerCoverageRoute: HomeownerCoverageRoute,
  WhyWeBuiltHppRoute: WhyWeBuiltHppRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
